name: MaxHungerFixer
version: 1.0.0-ALPHA
description: SpigotMC plugin that ensures users do not have more than 20.0 hunger points
author: lokka30
main: me.lokka30.maxhungerfixer.MaxHungerFixer
api-version: '1.13'